### ISSUE TITLE
Error upon submitting /newstory + Freeze after closing Newspaper

### ISSUE THREAD

**Issue by Duderocktv** [xFutte/qb-newsstands#2]
![image](https://user-images.githubusercontent.com/49062165/175426372-a1e0f5c2-4d41-4108-9c2a-79ca28f21817.png)

Hey so, I get the error posted here when I write
![image](https://user-images.githubusercontent.com/49062165/175426445-530fac93-2ef5-4754-a376-3ab8e89a44de.png)

Also when I "Read Newspaper" and then press ESC, I believe the NUI focus remains on even though the page closes. So I cannot move my character around at all.

PS: Would you like us to make this an item with animation that you can buy? (For QBCore?)
We are absolutely garbage with javascript / front end stuff but we could spruce this up for the QBCore framework

**Comment by xFutte** [comment]
@Duderocktv I'll take a look at it and see if I can reproduce the error. Furthermore, I'll add an item and add it to the README.md file including an image of a newspaper into an image folder which you put into the qb-inventory resource (or whatever you use).

**Comment by xFutte** [comment]
@Duderocktv I'm doing a complete overhaul of the resource.
